### ISSUE TITLE
Actividad 1,  Hernández Matra Jorge Luis grupo:1bs

### ISSUE THREAD

**Issue by JORGELUIS2266** [SistemasTecTlaxiaco/actividad-1-mapa-mental-JORGELUIS2266#1]
![MAPA MENTAL-HERNANDEZ MATRA JORGE LUIS](https://user-images.githubusercontent.com/112587421/187823119-5b618c05-e8f6-4c87-8854-501f2432ca3e.jpeg)

**Comment by josealfredo79** [comment]
Faltan algunos elementos...

**Comment by josealfredo79** [comment]
Calificacion 16

**Comment by josealfredo79** [comment]
Revisado
